import { Link } from 'react-router-dom';
import { useData } from '../context/DataContext';
import SEOHead from '../components/SEO/SEOHead';
import StructuredData from '../components/SEO/StructuredData';
import Breadcrumbs from '../components/Common/Breadcrumbs';
import FAQSection from '../components/SEO/FAQSection';
import Button from '../components/Common/Button';
import Card from '../components/Common/Card';
import { generateBreadcrumbSchema } from '../components/SEO/StructuredData';
import { typography, spacing } from '../utils/designTokens';

export default function Scholarships() {
  const { universities, loading } = useData();

  const breadcrumbs = [
    { name: 'Home', url: '/' },
    { name: 'Scholarships', url: '/scholarships' }
  ];

  const getUniversityScholarships = (university) => {
    const scholarships = [];
    
    if (university.id === 'niu') {
      scholarships.push({
        name: 'Bangladeshi Student Scholarship',
        percentage: 50,
        eligibility: 'All Bangladeshi students - No GPA requirement',
        description: 'NIU offers a flat 50% scholarship to all Bangladeshi students regardless of their GPA.',
        programs: 'All programs'
      });
    } else if (university.id === 'sharda') {
      scholarships.push(
        {
          name: 'High Performance Scholarship',
          percentage: 50,
          eligibility: 'GPA 3.5 - 5.0',
          description: '50% scholarship for high-performing students in Category 1 programs (B.Tech, BBA, MBA, etc.)',
          programs: 'B.Tech, BBA, MBA, BCA, MCA, B.Com, B.Arch, B.Design, BA Film/TV, LLB, BJMC, MJMC, M.Advertising, B.Sc. (Radiology, BMLT, CVT, Forensic, Optometry, Nutrition, Dialysis), M.Sc. (Clinical Research, Forensic, Nutrition)'
        },
        {
          name: 'Standard Scholarship',
          percentage: 20,
          eligibility: 'GPA 3.0 - 3.49',
          description: '20% scholarship for students with good academic performance in Category 1 programs',
          programs: 'Same as High Performance Scholarship'
        },
        {
          name: 'Nursing Scholarship',
          percentage: 25,
          eligibility: 'GPA 3.0 and above',
          description: '25% scholarship for B.Sc. Nursing program',
          programs: 'B.Sc. Nursing'
        },
        {
          name: 'Standard Scholarship (Category 3)',
          percentage: 20,
          eligibility: 'GPA 3.0 and above',
          description: '20% scholarship for other B.Sc., B.A., M.Sc., M.A. programs',
          programs: 'Other B.Sc., B.A., M.Sc., M.A. programs'
        },
        {
          name: 'Enhanced Scholarship (Category 3)',
          percentage: 30,
          eligibility: 'GPA 3.0 and above',
          description: '30% scholarship for select Category 3 programs',
          programs: 'Select B.Sc., B.A., M.Sc., M.A. programs'
        }
      );
    } else if (university.id === 'chandigarh') {
      scholarships.push(
        {
          name: 'High Performance Scholarship',
          percentage: 50,
          eligibility: 'GPA 3.5 and above',
          description: '50% scholarship for high-performing Bangladeshi students',
          programs: 'All programs'
        },
        {
          name: 'Standard Scholarship',
          percentage: 35,
          eligibility: 'GPA below 3.5',
          description: '35% scholarship for all other Bangladeshi students',
          programs: 'All programs'
        }
      );
    } else if (university.id === 'galgotias') {
      scholarships.push(
        {
          name: 'B.Tech Scholarship',
          percentage: 60,
          eligibility: 'All Bangladeshi students - No GPA requirement',
          description: '60% scholarship for all B.Tech programs',
          programs: 'All B.Tech programs'
        },
        {
          name: 'Other Programs Scholarship',
          percentage: 50,
          eligibility: 'All Bangladeshi students - No GPA requirement',
          description: '50% scholarship for all non-B.Tech programs',
          programs: 'All programs except B.Tech'
        }
      );
    }

    return scholarships;
  };

  // FAQPage schema is generated by FAQSection component below

  const faqs = [
    {
      question: "What scholarships are available for Bangladeshi students?",
      answer: "Bangladeshi students can avail generous scholarships at top Indian universities. NIU offers 50% flat scholarship to all students, Sharda offers 20-50% based on GPA, Chandigarh University offers 35-50% based on GPA, and Galgotias offers 50-60% based on program type. All scholarships are applied automatically upon admission."
    },
    {
      question: "Do I need a high GPA to get scholarships?",
      answer: "Not necessarily. NIU and Galgotias offer scholarships without GPA requirements. Sharda and Chandigarh University offer higher scholarships for students with GPA 3.5+, but also provide scholarships for students with lower GPAs. Check each university's specific eligibility criteria."
    },
    {
      question: "How do I apply for scholarships?",
      answer: "Scholarships are automatically applied when you apply through Western Bangla Education (WBE). No separate scholarship application is needed. WBE will help you understand which scholarship tier you qualify for based on your academic performance."
    },
    {
      question: "Are scholarships renewable every year?",
      answer: "Yes, most scholarships are applied annually throughout your program duration, as long as you maintain satisfactory academic performance. The scholarship percentage remains consistent each year."
    },
    {
      question: "What fees do scholarships cover?",
      answer: "Scholarships typically apply to tuition fees only. One-time admission fees, examination fees, and other charges are usually not covered by scholarships. Check the detailed fee breakdown for each program to understand what's included."
    }
  ];

  if (loading) {
    return (
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8" aria-live="polite" aria-busy="true">
        <div className="flex items-center justify-center min-h-[400px]">
          <div className="text-center">
            <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mb-4" role="status" aria-label="Loading">
              <span className="sr-only">Loading scholarships...</span>
            </div>
            <p className="text-gray-700" aria-live="polite">Loading scholarships...</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <>
      <SEOHead
        title="Scholarships for Bangladeshi Students in India 2025-26 - Up to 60% Off Tuition Fees | WBE"
        description="Complete guide to scholarships for Bangladeshi students at top Indian universities. NIU: 50% flat (no GPA required), Sharda: 20-50% (GPA-based), Chandigarh: 35-50% (GPA-based), Galgotias: 50-60% (program-based). Eligibility criteria, application process, and renewal terms. Free counseling by Western Bangla Education."
        keywords={[
          'scholarships for Bangladeshi students in India',
          'India scholarships for Bangladeshi students',
          'university scholarships India',
          'study in India scholarships',
          'WBE scholarships',
          'Western Bangla Education scholarships',
          'NIU scholarship',
          'Sharda University scholarship',
          'Chandigarh University scholarship',
          'Galgotias University scholarship',
          'free education India',
          'scholarship eligibility',
          'GPA based scholarship',
          'tuition fee discount India',
          'affordable education India'
        ]}
        url="/scholarships"
        canonical="/scholarships"
      />
      {generateBreadcrumbSchema(breadcrumbs) && <StructuredData data={generateBreadcrumbSchema(breadcrumbs)} />}
      {/* FAQPage schema is generated by FAQSection component below */}
      <Breadcrumbs items={breadcrumbs} />

      <div className={`max-w-7xl mx-auto ${spacing.container} ${spacing.sectionSmall}`}>
        <div className="text-center mb-8 sm:mb-12">
          <h1 className={`${typography.sectionTitle} mb-4 sm:mb-6 text-gray-900`}>Scholarships for Bangladeshi Students in India</h1>
          <p className={`${typography.bodyLarge} max-w-3xl mx-auto leading-relaxed`}>
            Comprehensive guide to all available scholarships for Bangladeshi students at top Indian universities. 
            Get up to 60% scholarship on tuition fees. Apply through Western Bangla Education for free counseling and scholarship assistance.
          </p>
        </div>

        {/* University Scholarships */}
        <div className="space-y-8 mb-12">
          {universities.map(university => {
            const scholarships = getUniversityScholarships(university);
            if (scholarships.length === 0) return null;

            return (
              <Card key={university.id} variant="default" borderColor="border-blue-200" className="border-2">
                <div className="mb-6">
                  <div className="flex items-center space-x-3 mb-3">
                    <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-indigo-500 rounded-xl flex items-center justify-center shadow-md" aria-hidden="true">
                      <span className="text-white font-bold text-lg">{university.shortName.charAt(0)}</span>
                    </div>
                    <div>
                      <h2 className={`${typography.sectionTitle} text-gray-900`}>{university.name}</h2>
                      <p className={typography.caption}>{university.location}</p>
                    </div>
                  </div>
                </div>

                <div className="space-y-4 sm:space-y-5">
                  {scholarships.map((scholarship, index) => (
                    <Card key={index} variant="gradient" gradientColors="from-gray-50 to-blue-50" className="border border-gray-200">
                      <div className="flex flex-col sm:flex-row justify-between items-start mb-4">
                        <div className="flex-1 mb-3 sm:mb-0">
                          <h3 className={`${typography.cardTitle} mb-2 text-gray-900`}>{scholarship.name}</h3>
                          <p className={`${typography.body} leading-relaxed`}>{scholarship.description}</p>
                        </div>
                        <div className="text-center sm:text-right ml-0 sm:ml-4 bg-white rounded-xl p-4 shadow-sm border border-green-200">
                          <div className="text-3xl sm:text-4xl font-bold text-green-600">{scholarship.percentage}%</div>
                          <div className={`${typography.caption} font-medium`}>Scholarship</div>
                        </div>
                      </div>
                      <div className="mt-4 pt-4 border-t border-gray-200">
                        <div className={`grid grid-cols-1 md:grid-cols-2 ${spacing.gapSmall} text-sm`}>
                          <Card variant="default" className="p-3">
                            <span className={`${typography.label}`}>Eligibility:</span>
                            <p className={`${typography.body} mt-1`}>{scholarship.eligibility}</p>
                          </Card>
                          <Card variant="default" className="p-3">
                            <span className={typography.label}>Applicable Programs:</span>
                            <p className={`${typography.body} mt-1`}>{scholarship.programs}</p>
                          </Card>
                        </div>
                      </div>
                    </Card>
                  ))}
                </div>

                <div className="mt-6 pt-6 border-t border-gray-200">
                  <Link
                    to={`/universities/${university.slug}`}
                    className="text-blue-600 hover:text-blue-800 font-semibold inline-flex items-center group"
                  >
                    View {university.name} Details
                    <svg className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                    </svg>
                  </Link>
                </div>
              </Card>
            );
          })}
        </div>

        {/* FAQ Section */}
        <FAQSection faqs={faqs} title="Frequently Asked Questions about Scholarships" />

        {/* CTA Section */}
        <section className={`bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 text-white ${spacing.card} rounded-xl text-center mt-12 shadow-large relative overflow-hidden`}>
          <div className="absolute inset-0 bg-grid-pattern opacity-10"></div>
          <div className="relative z-10">
            <h2 className={`${typography.sectionTitle} mb-4 sm:mb-6`}>Ready to Apply for Scholarships?</h2>
            <p className={`${typography.bodyLarge} mb-6 sm:mb-8 text-blue-50 max-w-2xl mx-auto`}>
              Get free counseling and scholarship assistance from Western Bangla Education. 
              We'll help you understand which scholarships you qualify for and guide you through the application process.
            </p>
            <Button to="/apply" variant="white" size="md">
              Apply Now - Free Consultation
            </Button>
          </div>
        </section>
      </div>
    </>
  );
}

